### PR TITLE
Features/show fps

### PR DESCRIPTION
**Pull request by yuhangzheng94**
The widget is by default placed on the top left corner of the web page. A screenshot:
image

~75fps looks surprising high (my benchmark was usually 35/60) so I'm not sure if I did it right. I wrap `stats.begin()` and `stats.end()` around everything within `draw()` of the `p5` instance.

### CODE REVIEW

**Comment by osteele** [comment]
> 75fps looks surprising high (my benchmark was usually 35/60) so I'm not sure if I did it right. I wrap stats.begin() and stats.end() around everything within draw() of the p5 instance

That's finding the fps of the draw loop. This is different from the fps of pose recognition. Pose recognition runs asynchronously, updating the global data structure (and sending the new data to the server) whenever BlazePose signals that a new pose is ready. The draw loop runs at a fixed rate (unless some code is taking more than 1/60 seconds, in which case it has to run slower). It will use the same pose for rendering multiple frames, so that the rendering fps could be 60 while the pose recognition fps could be much slower. Also, the fps for image data (from the web cam), pose data from the local user, and pose data from other users, could all be running at different frame rates (although if any of them is faster than the rendering fps, the user won't see that).

**Comment by yuhangzheng94** [comment]
I move the usage of `stats.js` code from `sketch.ts` to `blazePose.js` to reflect pose detection frequency:
```typescript
export async function initializeBlazePose(
  video: HTMLVideoElement
): Promise<void> {
  
  // omitted content

  async function loop() {
    loopIsRunning = true;
    while (true) {
      // stats begin
      stats.begin();

      // omitted content

      // stats end
      stats.end();
    }
  }
}
```

 The FPS display looks closer to reality now:
image

**Comment by osteele** [comment]
Looks great, almost there. I recommend changing `sketch.ts` back to its original state, instead of the lines that are added and then commented out. You can do this manually, or from the command line via `git checkout main -- src/sketch.ts`

**Comment by yuhangzheng94** [comment]
Done!

**Review by osteele — APPROVED** [review]

**Pull request merged**
